SELECT * FROM USERS;

-- SELECT * FROM USERS WHERE NAME = 'John' OR NAME = 'Anuj';

-- SELECT * FROM USERS WHERE NAME IN ('John', 'Anuj');

-- SELECT LOWER(NAME) FROM USERS WHERE NAME = 'John' AND EMAIL = 'John@gmail.com';

-- SELECT * FROM USERS WHERE NOT AGE = 20;

-- SELECT * FROM USERS WHERE AGE BETWEEN 20 AND 30;

-- SELECT * FROM USERS WHERE NAME LIKE '%n';



