-- INSERT INTO PRODUCT VALUES (3, 'Banana', 30);


-- SELECT TOP 1 * FROM PRODUCT;

-- UPDATE PRODUCT SET PRICE = 20 WHERE ID = 1;

-- ALTER TABLE PRODUCT ADD COLUMN QUANTITY INT DEFAULT 0;

-- ALTER TABLE PRODUCT DROP COLUMN QUANTITY;

SELECT SUM(QUANTITY) AS TOTAL_QUANTITY FROM PRODUCT;